### ISSUE TITLE
Basic Usage example doesn't work on 1.6.0 and 1.6.1

### ISSUE THREAD

**Issue by Popolon** [Kozea/cairocffi#220]
I tried the [Basic Usage Example](https://doc.courtbouillon.org/cairocffi/stable/overview.html#basic-usage) from the documentation of  python-cairocffi

And with 1.6.0 (current official Arch package) and 1.6.1 on Arch Linux, it fails with the following error:
<pre>
$ python cairocffi.py
Traceback (most recent call last):
  File "/tmp/cairocffi.py", line 1, in <module>
    import cairocffi as cairo
  File "/tmp/cairocffi.py", line 3, in <module>
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 300, 200)
              ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'cairocffi' has no attribute 'ImageSurface' (most likely due to a circular import)
</pre>

**Comment by liZe** [comment]
Hi!

The example works correctly for me. It doesn’t for you probably because you named your file `cairocffi.py`, and thus the import loads the file itself instead of loading the library.
